### ISSUE TITLE
Add demo website

### ISSUE THREAD

**Issue by teobais** [teobais/percircle-vue#2]
Just like in percircle: new branch to host a live version of percircle-vue

**Comment by richardsaseun14** [comment]
Hello @teobais. Can i jump on this issue?

**Comment by teobais** [comment]
Hey, @richardsaseun14 , sure! Assigning this to you.

**Comment by richardsaseun14** [comment]
Thanks, @teobais for assigning me this issue. 

Just to clarify what I am to do. I am to create a new branch and create a new website for percircle-vue which looks like the original percircle website right?

Do you have any steps for me to follow?

**Comment by teobais** [comment]
@richardsaseun14 exactly.

1. new branch `gh-pages` so that it can automatically be hosted under teobais.github.io/percircle-vue
2. this website should be showcasing the features of percircle-vue, just like teobais.github.io/percircle does
3. submit a PR for the newly introduced branch (`gh-pages`) so that we can review

Bonus points
- feel free to be creative and even improve the website where needed (a good starting point might already be the current look 'n feel of percircle-vue - the local index.html you can once you run it locally)

Side note: I know this might still sound a bit vague, so I would suggest opening a PR or posting a screenshot with the first increment here once ready, and we take it from there.

Let me know if there are any further questions

**Comment by richardsaseun14** [comment]
@teobais thanks!

This helps.

**Comment by richardsaseun14** [comment]
@teobais  Can I install a ui framework like bootstrapvue ?

**Comment by miller-kevin** [comment]
@richardsaseun14 @teobais is the boss, so he may say differently, but since I'm online I figured I may as well chime in.

As long as bootstrap-vue is a dependency of the demo site and not a dependency of the percircle.vue component, I don't see why you couldn't use any package you'd like for your purposes

**Comment by richardsaseun14** [comment]
> @richardsaseun14 @teobais is the boss, so he may say differently, but since I'm online I figured I may as well chime in.
> 
> As long as bootstrap-vue is a dependency of the demo site and not a dependency of the percircle.vue component, I don't see why you couldn't use any package you'd like for your purposes

@miller-kevin okay that sounds good. i will install bootstrap-vue and give it a test
