### ISSUE TITLE
Add contributors section in package-json

### ISSUE THREAD

**Issue by teobais** [teobais/percircle-vue#6]
Add Kevin Miller as a contributor in package-json

**Comment by Aman-Mandal** [comment]
Hey .. Can I take this issue? And if yes..Can you guide me as am very new to open source

**Comment by teobais** [comment]
Hey @Aman-Mandal , thank you for your interest in `percircle-vue` 🙌 . The main idea of this issue is to add a "contributors" section in package-json file, listing the maintainers of this project. To begin with, we could start with adding Kevin Miller. You can find an example on how to add a contributors list in package-json [here](https://flaviocopes.com/package-json/#contributors).

@miller-kevin could you please help by letting us know of your email and website, so Aman could add them accordingly? Thanks

@Aman-Mandal assigning this to you

**Comment by Aman-Mandal** [comment]
Hello @miller-kevin , can you please provide me your email and website ? Thankyouuu.

**Comment by miller-kevin** [comment]
@teobais @Aman-Mandal For url, just use my GitHub link - https://github.com/miller-kevin, and I don't have a catch all email, just my personal which I'd rather not publish. Email and url are optional fields, so feel free to just include my name and that GitHub link

**Comment by Aman-Mandal** [comment]
Hello, Can you please check my PR .   :)

**Comment by miller-kevin** [comment]
@Aman-Mandal thanks!

**Comment by Aman-Mandal** [comment]
> @Aman-Mandal thanks!

Thanks to You Sir.. I did my very first open-source contribution. Feeling so good : )
